version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=sql333
      - MYSQL_DATABASE=airlines_management_system
    ports:
      - "3307:3306"
  app:
    depends_on:
      - mysqldb
    image: vidzivashets/airlines-app
    build: .
    env_file: ./.env
    ports:
      - "6868:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/airlines_management_system?serverTimezone=UTC&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "sql333",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "create"
      }'
